openapi: "3.0.3"
info:
  title: Notification sending status management API
  description: お知らせの送付状況管理アプリ仕様書です。
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: notification
    description: 送付状況の管理に関する操作
  - name: mail
    description: メール送信に関する操作
paths:
  /notifications:
    get:
      tags:
        - notification
      summary: お知らせ送付状況の取得
      description: クエリパラメータで入力された条件に合致する人の送付状況を取得する。条件を入力しない場合は全ての人の送付状況を取得する
      parameters:
        - name: name
          in: query
          description: 名前に入力した文字が含まれる人の送付状況が検索される
          required: false
          schema:
            type: string
          example: 田中　太郎
        - name: Elapsed days
          in: query
          description: 送付後指定した日数以上経過した人の送付状況が検索される
          required: false
          schema:
            type: int
          example: 21
        - name: sending times
          in: query
          description: 送付回数が入力した回数の人の送付状況が検索される
          required: false
          schema:
            type: int
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    notificationId:
                      type: int
                      example: 1
                    name:
                      type: string
                      example: 田中　太郎
                    address:
                      type: string
                      example: 東京
                    posting date:
                      type: String
                      example: 2023-01-01
                    sending times:
                      type: int
                      example: 1
                    response:
                      type: string
                      example: 有り
                  
    post:
      tags:
        - notification
      summary: 送付状況の新規登録
      description: 送付状況を新たに登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: false
                  example: 田中　太郎
                address:
                  type: string
                  nullable: false
                  example: 東京  
                posting date:
                  type: string
                  nullable: false
                  example: 2023-01-01
                sending times:
                  type: int
                  nullable: false
                  example: 1
                response:
                  type: string
                  nullable: false
                  example: 有り
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 送付状況が正常に登録されました
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestNotification'
                
  /notifications/{notificationId}:
    patch:
      tags:
        - notification
      summary: 送付状況の更新
      description: 指定した条件の送付状況を更新する
      parameters:
        - name: notificationId
          in: path
          description: 更新したい送付状況のID
          required: true
          schema:
          type: int
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: false
                  example: 田中　太郎
                address:
                  type: string
                  nullable: false
                  example: 東京  
                posting date:
                  type: string
                  nullable: false
                  example: 2023-01-01
                sending times:
                  type: int
                  nullable: false
                  example: 1
                response:
                  type: string
                  nullable: false
                  example: 有り
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 送付状況が正常に更新されました
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestNotification'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
                
    delete:
      tags:
        - notification
      summary: 送付状況の削除
      description: 指定したIDの送付状況を削除する
      parameters:
        - name: notificationId
          in: path
          description: 削除したい送付状況のID
          required: true
          schema:
          type: int
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 送付状況が正常に削除されました
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
  
components:
  schemas:
    BadRequestNotification:
      description: 送付状況に関する操作でリクエストボディに不備がある場合のレスポンス
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: 入力情報に不備が有ります。
        path:
          type: string
          example: 指定したパス
    NotFound:
      description: 指定したリソースが存在しない場合のレスポンス
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          example: 404
        error:
          type: string
          example: Not Found
        message:
          type: string
          example: Not Found
        path:
          type: string
          example: 指定したパス