openapi: "3.0.3"
info:
  title: Notification management API
  description: お知らせの送付状況管理アプリ仕様書です。
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: notification
    description: 送付状況の管理に関する操作
paths:
  /notifications:
    get:
      tags:
        - notification
      summary: お知らせ送付状況の取得
      description: クエリパラメータで入力された条件に合致する人の送付状況を取得する。条件を入力しない場合は全ての人の送付状況を取得する
      parameters:
        - name: name
          in: query
          description: 名前に入力した文字が含まれる人の送付状況が検索される
          required: false
          schema:
            type: string
          example: 田中　太郎
        - name: elapsedDays
          in: query
          description: 送付後指定した日数以上経過した人の送付状況が検索される
          required: false
          schema:
            type: int
          example: 21
        - name: sendingTimes
          in: query
          description: 送付回数が入力した回数の人の送付状況が検索される
          required: false
          schema:
            type: int
          example: 1
        - name: response
          in: query
          description: 入力した送付状況に該当する人の送付状況が検索される
          required: false
          schema:
            type: string
          example: 有り
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: int
                      example: 1
                    name:
                      type: string
                      example: 田中　太郎
                    address:
                      type: string
                      example: 東京
                    postingDate:
                      type: String
                      example: 2023-01-01
                    sendingTimes:
                      type: int
                      example: 1
                    response:
                      type: string
                      example: 有り
        "400":
          description:  BadRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  status:
                    type: string
                    example: 400
                  error:
                    type: string
                    example: Bad Request
                  path:
                    type: string
                    example: 指定したパス
                
                  
    post:
      tags:
        - notification
      summary: 送付状況の新規登録
      description: 送付状況を新たに登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: false
                  example: 田中　太郎
                address:
                  type: string
                  nullable: false
                  example: 東京  
                postingDate:
                  type: string
                  nullable: false
                  example: 2023-01-01
                sendingTimes:
                  type: int
                  nullable: false
                  example: 1
                response:
                  type: string
                  nullable: false
                  example: 有り
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: notification successfully created
        "400":
          description:  Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  status:
                    type: string
                    example: 400
                  error:
                    type: string
                    example: Bad Request
                  path:
                    type: string
                    example: 指定したパス
                
  /notifications/{id}:
    patch:
      tags:
        - notification
      summary: 送付状況の更新
      description: 指定した条件の送付状況を更新する
      parameters:
        - name: id
          in: path
          description: 更新したい送付状況のID
          required: true
          schema:
          type: int
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: false
                  example: 田中　太郎
                address:
                  type: string
                  nullable: false
                  example: 東京  
                postingDate:
                  type: string
                  nullable: false
                  example: 2023-01-01
                sendingTimes:
                  type: int
                  nullable: false
                  example: 1
                response:
                  type: string
                  nullable: false
                  example: 有り
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: notification successfully updated
        "400":
          description:  BadRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  status:
                    type: string
                    example: 400
                  error:
                    type: string
                    example: Bad Request
                  path:
                    type: string
                    example: 指定したパス
                
    delete:
      tags:
        - notification
      summary: 送付状況の削除
      description: 指定したIDの送付状況を削除する
      parameters:
        - name: id
          in: path
          description: 削除したい送付状況のID
          required: true
          schema:
          type: int
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: notification successfully deleted
                    